### ISSUE TITLE
Bug: stack trace popup when blink device not found

### ISSUE THREAD

**Issue by tedpennings** [bettse/teamblink#17]
My blink device didn't seem to be registering with the Electron control app, so I tried to change my color to see if that would have an impact. Nope -- stack trace popup!

Note: this did not segfault the app or cause it to quit. Just a popup

![slack_-_invisionapp_and_1password](https://cloud.githubusercontent.com/assets/310323/20399886/8d49b8e8-aca7-11e6-9257-4118ecb4c650.png)

**Comment by bettse** [comment]
note to self: https://github.com/MadLittleMods/node-usb-detection/
